# PlatformIO pre-script: compile default home Wi-Fi credentials and the Wi-Fi
# update token from wifi_secrets.ini.
#
# wifi_secrets.ini is gitignored. Its values go into a generated header in the
# build directory rather than -D flags, so any characters work and they never
# appear on compiler command lines. Without the file the strings are empty: the
# badge relies on settings saved through its hotspot page and Wi-Fi updates are off.
import configparser
import os
import re
import string

Import("env")  # noqa: F821 - provided by SCons

SECRETS_FILE = os.path.join(env.subst("$PROJECT_DIR"), "wifi_secrets.ini")  # noqa: F821
INCLUDE_DIR = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
HEADER = os.path.join(INCLUDE_DIR, "home_wifi_secrets.h")
SAFE_CHARS = set((string.ascii_letters + string.digits + " !#$%&'()*+,-./:;<=>@[]^_`{|}~").encode())


def fail(message):
    print(f"Error: {SECRETS_FILE}: {message}")
    env.Exit(1)  # noqa: F821


def c_string(value):
    # Octal escapes are at most three digits, so they never merge with what follows.
    return '"' + "".join(chr(b) if b in SAFE_CHARS else f"\\{b:03o}" for b in value) + '"'


ssid = password = token = b""
if os.path.isfile(SECRETS_FILE):
    config = configparser.ConfigParser(interpolation=None)
    config.read(SECRETS_FILE, encoding="utf-8")
    ssid = config.get("wifi", "ssid", fallback="").encode()
    password = config.get("wifi", "password", fallback="").encode()
    if not 1 <= len(ssid) <= 32:
        fail("[wifi] ssid must be 1-32 bytes")
    hex_key = len(password) == 64 and all(chr(b) in string.hexdigits for b in password)
    if not (8 <= len(password) <= 63 or hex_key):
        fail("[wifi] password must be 8-63 characters (or 64 hex digits)")
    token = config.get("ota", "token", fallback="").encode()
    if token and not re.fullmatch(rb"[A-Za-z0-9_-]{16,100}", token):
        fail("[ota] token must be 16-100 letters, digits, '-' or '_'")

header = (
    "// Generated by scripts/wifi_secrets.py from wifi_secrets.ini. Do not commit.\n"
    "#pragma once\n"
    f"#define HOME_WIFI_BUILD_SSID {c_string(ssid)}\n"
    f"#define HOME_WIFI_BUILD_PASSWORD {c_string(password)}\n"
    f"#define HOME_OTA_TOKEN {c_string(token)}\n"
)
os.makedirs(INCLUDE_DIR, exist_ok=True)
current = open(HEADER).read() if os.path.exists(HEADER) else None
if header != current:
    with open(HEADER, "w") as f:
        f.write(header)
env.Append(CPPPATH=[INCLUDE_DIR])  # noqa: F821
